plugins {
    id 'io.micronaut.build.internal.module'
    id 'io.micronaut.build.internal.rss-base'
}


dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor mnValidation.micronaut.validation.processor
    implementation mnValidation.micronaut.validation

    compileOnly libs.findbugs // for "warning: unknown enum constant When.MAYBE"
    testCompileOnly libs.findbugs // for "warning: unknown enum constant When.MAYBE"
}
//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force "org.spockframework:spock-core:2.4-M7-groovy-5.0"
    }
}