pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("io.micronaut.build.shared.settings") version "8.1.1"
}

rootProject.name = 'rss-parent'

include 'rss'
include 'rss-bom'
include 'rss-core'
include 'itunespodcast'
include 'jsonfeed-core'
include 'jsonfeed'
include 'rss-language'

include 'test-suite'
include 'test-suite-kotlin'
include 'test-suite-groovy'
include 'test-suite-python'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-validation")
}
