[versions]

findbugs = "3.0.2"

micronaut-serde = "2.0.0-M1"
micronaut-validation = "4.0.0-SNAPSHOT"

micronaut-docs = "2.0.0"
micronaut = "4.0.0-M1"
micronaut-test = "4.0.0-SNAPSHOT"
groovy = "4.0.10"
spock = "2.3-groovy-4.0"

[libraries]

findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }

micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

groovy-xml = { module = "org.apache.groovy:groovy-xml" }
