[versions]

findbugs = "3.0.2"

micronaut-serde = "2.0.0-SNAPSHOT"
micronaut-test = "4.0.0-SNAPSHOT"

[libraries]

findbugs = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }

micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }

groovy-xml = { module = "org.apache.groovy:groovy-xml" }
